### ISSUE TITLE
Cannot find 'knReg' in fun_gp.m

### ISSUE THREAD

**Issue by fkmajiji** [tendence/refl_L1#1]
Hello tendence, thank you very much for your hard work! Your code contains multiple methods, it will help the new learner like me to understand the spectral reconstruction. But when I run the 'one_vs_all_3_method.m', it got a error message:"cannot find the function or variable 'knReg' in line36 of func_gp". Do you know the reason? 

Looking for your reply!

All the best,
Kai

**Comment by tendence** [comment]
Hi， please find the function in PRMLT repository.

Thank you for using the code.

**Comment by fkmajiji** [comment]
Thank you very much, I have found it and runned the code.
